### ISSUE TITLE
Docs branch is not being updated

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-language#150]
The workflow that updates the docs branch after a commit to main is failing on the "push changes" step. For example, https://github.com/microsoft/qsharp-language/runs/7240543495:

```
Run ad-m/github-push-action@master
Push to branch ⭐Docs
POST git-receive-pack (1[8](https://github.com/microsoft/qsharp-language/runs/7240543495#step:4:9)887 bytes)
remote: fatal error in commit_refs        
Pushing to https://github.com/microsoft/qsharp-language.git
To https://github.com/microsoft/qsharp-language.git
 ! [remote rejected] HEAD -> ⭐Docs (failure)
error: failed to push some refs to 'https://github.com/microsoft/qsharp-language.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (D:\a\_actions\ad-m\github-push-action\master\start.js:2[9](https://github.com/microsoft/qsharp-language/runs/7240543495#step:4:10):21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:[10](https://github.com/microsoft/qsharp-language/runs/7240543495#step:4:11)22:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (D:\a\_actions\ad-m\github-push-action\master\start.js:29:21)
    at ChildProcess.emit (events.js:3[14](https://github.com/microsoft/qsharp-language/runs/7240543495#step:4:15):20)
    at maybeClose (internal/child_process.js:1022:[16](https://github.com/microsoft/qsharp-language/runs/7240543495#step:4:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by samarsha** [comment]
@cgranade do you know what might be happening?

**Comment by samarsha** [comment]
The last 3 runs have mysteriously started working again...

**Comment by samarsha** [comment]
In any case, I think it's a bug that the actions do not specify a version:

- actions/checkout@master
- ad-m/github-push-action@master

So any changes to those repos can spontaneously break our CI. I think we should use verison tags.
